name: DomesticatedIris
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Domesticated Iris - Entrepreneurial crafts by Danielle Iris
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#663397'
    - '#000000'
    - '#ff00ff'
    - '#c2afd6'
    - '#ffff00'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
