name: DomesticatedIris
favicon: null
layout_spectrum: 0.7804028815589845
typography_spectrum: 0.38851020601578057
title: Domesticated Iris - Entrepreneurial crafts by Danielle Iris
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3517089164815843
  lightness: 0.7193013944197446
  saturation: 0.8544761328957975
  rhythmicContrast: 0.7786556333303452
purpose: []
